name: Pull Request Open

on:
  pull_request:
    branches: [main]
    workflow_dispatch:

jobs:
  Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd infrastructure
          npm ci

      - name: Check formatting 
        run: prettier --check .